<?php

declare(strict_types=1);

namespace RowBuddy\Bids\Application;

use RowBuddy\Bids\Bid;
use RowBuddy\Bids\Contracts\BidPlacementLedger;
use RowBuddy\Bids\Contracts\BidRepository;
use RowBuddy\Bids\Exceptions\AuctionNotOpenForBidding;
use RowBuddy\Bids\Exceptions\BidderAccountSuspended;
use RowBuddy\Bids\Exceptions\BidIdempotencyKeyReused;
use RowBuddy\Bids\Exceptions\BidPlacementInProgress;
use RowBuddy\Bids\Exceptions\BidTooLow;
use RowBuddy\Bids\Exceptions\CurrencyMismatch;
use RowBuddy\Bids\Exceptions\SellerCannotBidOnOwnAuction;
use RowBuddy\Bids\ValueObjects\BidClaimResult;
use RowBuddy\Bids\ValueObjects\BidRejectionReason;
use RowBuddy\SharedKernel\Exceptions\NotFoundException;
use RowBuddy\SharedKernel\ValueObjects\Money;
use Throwable;

/**
 * A drop-in, duplicate-safe wrapper around {@see BidService::place()}
 * (Phase 9, ADR-027 Architecture Refinements §2): same return type, same
 * thrown exception types on a fresh request, so a network retry carrying
 * the same Idempotency-Key gets back the exact same outcome instead of
 * placing (or attempting to place) a second bid. Never touches
 * BidService's own transaction or row-lock behavior — it only decides,
 * before and after, whether BidService should be called at all.
 */
final class IdempotentBidPlacementService
{
    public function __construct(
        private readonly BidService $bidService,
        private readonly BidPlacementLedger $ledger,
        private readonly BidRepository $bids,
    ) {}

    /**
     * $bidId must be freshly generated by the caller (mirroring
     * BidService::place() itself) only if this call turns out to be a
     * fresh claim — a replayed claim never uses it.
     *
     * @throws NotFoundException if the auction does not exist
     * @throws AuctionNotOpenForBidding
     * @throws CurrencyMismatch
     * @throws SellerCannotBidOnOwnAuction
     * @throws BidTooLow
     * @throws BidderAccountSuspended
     * @throws BidIdempotencyKeyReused if this key
     *                                 was already used for a different request
     * @throws BidPlacementInProgress if this key
     *                                is already being resolved by a concurrent request
     */
    public function place(string $idempotencyKey, string $bidId, string $auctionId, string $bidderId, Money $amount): Bid
    {
        $fingerprint = self::fingerprint($auctionId, $amount);

        $claim = $this->ledger->claim($bidderId, $idempotencyKey, $auctionId, $fingerprint);

        if ($claim->isResolved()) {
            return $this->replay($claim, $auctionId, $bidderId);
        }

        try {
            $bid = $this->bidService->place($bidId, $auctionId, $bidderId, $amount);
        } catch (Throwable $e) {
            $reason = self::rejectionReasonFor($e);

            if ($reason === null) {
                $this->ledger->release($bidderId, $idempotencyKey);

                throw $e;
            }

            $this->ledger->recordRejected($bidderId, $idempotencyKey, $reason);

            throw $e;
        }

        $this->ledger->recordAccepted($bidderId, $idempotencyKey, $bid->id);

        return $bid;
    }

    private function replay(BidClaimResult $claim, string $auctionId, string $bidderId): Bid
    {
        if ($claim->bidId !== null) {
            $bid = $this->bids->findById($claim->bidId);

            if ($bid !== null) {
                return $bid;
            }
        }

        $this->throwFor($claim->rejectionReason, $auctionId, $bidderId);
    }

    /**
     * @return never
     */
    private function throwFor(?BidRejectionReason $reason, string $auctionId, string $bidderId): void
    {
        throw match ($reason) {
            BidRejectionReason::AuctionNotFound => new NotFoundException("Auction [{$auctionId}] not found."),
            BidRejectionReason::AuctionNotOpenForBidding => AuctionNotOpenForBidding::forAuction($auctionId),
            BidRejectionReason::CurrencyMismatch => CurrencyMismatch::forAuction($auctionId),
            BidRejectionReason::SellerCannotBidOnOwnAuction => SellerCannotBidOnOwnAuction::forAuction($auctionId),
            BidRejectionReason::BidTooLow => BidTooLow::forAuction($auctionId),
            BidRejectionReason::BidderAccountSuspended => BidderAccountSuspended::forBidder($bidderId),
            null => throw new \RuntimeException("Resolved bid claim for auction [{$auctionId}] has neither a bid id nor a rejection reason."),
        };
    }

    private static function rejectionReasonFor(Throwable $e): ?BidRejectionReason
    {
        return match (true) {
            $e instanceof NotFoundException => BidRejectionReason::AuctionNotFound,
            $e instanceof AuctionNotOpenForBidding => BidRejectionReason::AuctionNotOpenForBidding,
            $e instanceof CurrencyMismatch => BidRejectionReason::CurrencyMismatch,
            $e instanceof SellerCannotBidOnOwnAuction => BidRejectionReason::SellerCannotBidOnOwnAuction,
            $e instanceof BidTooLow => BidRejectionReason::BidTooLow,
            $e instanceof BidderAccountSuspended => BidRejectionReason::BidderAccountSuspended,
            default => null,
        };
    }

    private static function fingerprint(string $auctionId, Money $amount): string
    {
        return hash('sha256', $auctionId.'|'.$amount->minorUnits.'|'.(string) $amount->currency);
    }
}
